#include "driver/gpio.h"
#include "esp_err.h"
#include "esp_log.h"
#include "hal/adc_types.h"
#include "hal/gpio_types.h"
#include "hal/ledc_types.h"
#include "pins.hpp"
#include "soc/clk_tree_defs.h"
#include "soc/gpio_num.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_adc/adc_oneshot.h"
#include "driver/ledc.h"
#include <cstddef>
#include <cstdint>
#include <atomic>
#include "driver/i2s_std.h"

static const char* TAG = "main";
static constexpr bool debug = false;

/*
gpio_num_t buzzer_pin = Board::D7;
gpio_config_t buzzer = {};
ledc_timer_config_t buzzer_timer = {};
ledc_channel_config_t buzzer_channel = {};
*/
gpio_num_t button_big_pin = Board::D8;
gpio_config_t button_big = {};

gpio_num_t ec11_pin1 = Board::D10;
gpio_num_t ec11_pin2 = Board::D9;
//gpio_num_t ec11_pin3 = Board::D2;
gpio_config_t ec11 = {};

gpio_num_t max98357a_blk = Board::D2; // BCLK
gpio_num_t max98357a_ws = Board::D7; // LRC
gpio_num_t max98357a_data = Board::D6; // DIN
int16_t *max98357a_buffer = new int16_t[2048];

void setup_gpio() {
    /*buzzer.pin_bit_mask = 1ULL << buzzer_pin;
    buzzer.mode = GPIO_MODE_OUTPUT;
    buzzer.pull_down_en = GPIO_PULLDOWN_DISABLE;
    buzzer.pull_up_en = GPIO_PULLUP_DISABLE;
    buzzer.intr_type = GPIO_INTR_DISABLE;
    gpio_config(&buzzer);*/
    // button
    button_big.pin_bit_mask = 1ULL << button_big_pin;
    button_big.mode = GPIO_MODE_INPUT;
    button_big.pull_up_en = GPIO_PULLUP_ENABLE;
    button_big.pull_down_en = GPIO_PULLDOWN_DISABLE;
    button_big.intr_type = GPIO_INTR_DISABLE;
    gpio_config(&button_big);
    // ec11 rotary encoder
    ec11.pin_bit_mask = 1ULL << ec11_pin1;
    ec11.mode = GPIO_MODE_INPUT;
    ec11.pull_up_en = GPIO_PULLUP_ENABLE;
    ec11.pull_down_en = GPIO_PULLDOWN_DISABLE;
    ec11.intr_type = GPIO_INTR_DISABLE;
    gpio_config(&ec11);
    ec11.pin_bit_mask = 1ULL << ec11_pin2;
    gpio_config(&ec11);
    //ec11.pin_bit_mask = 1ULL << ec11_pin3;
    //gpio_config(&ec11);
}

static i2s_chan_handle_t tx_handle;
void i2s_setup(gpio_num_t bclk_pin, gpio_num_t ws_pin, gpio_num_t dout_pin, uint32_t sample_rate = 44100) {
    /* Get the default channel configuration by the helper macro.
    * This helper macro is defined in `i2s_common.h` and shared by all the I2S communication modes.
    * It can help to specify the I2S role and port ID */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    chan_cfg.auto_clear = true;
    /* Allocate a new TX channel and get the handle of this channel */
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, &tx_handle, NULL));
    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(sample_rate),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = bclk_pin,
            .ws = ws_pin,
            .dout = dout_pin,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    /* Initialize the channel */
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_handle, &std_cfg));
    /* Before writing data, start the TX channel first */
    i2s_channel_enable(tx_handle); 
    /* If the configurations of slot or clock need to be updated,
    * stop the channel first and then update it */
    // i2s_channel_disable(tx_handle);
    // std_cfg.slot_cfg.slot_mode = I2S_SLOT_MODE_MONO; // Default is stereo
    // i2s_channel_reconfig_std_slot(tx_handle, &std_cfg.slot_cfg);
    // std_cfg.clk_cfg.sample_rate_hz = 96000;
    // i2s_channel_reconfig_std_clock(tx_handle, &std_cfg.clk_cfg);
}

void i2s_write(int16_t *buffer, size_t buffer_size) {
    size_t bytes_written;
    esp_err_t ret = i2s_channel_write(tx_handle, buffer, buffer_size, &bytes_written, portMAX_DELAY);
    if (ret == ESP_OK) {
        ESP_LOGI("i2s", "i2s wrote %d bytes", bytes_written);
    } else {
        ESP_LOGE("i2s", "i2s write failed");
    }
}

void i2s_deinit() {
    /* Have to stop the channel before deleting it */
    ESP_ERROR_CHECK(i2s_channel_disable(tx_handle));
    /* If the handle is not needed any more, delete it to release the channel resources */
    i2s_del_channel(tx_handle);
}

void generate_test_tone(int16_t *buffer, size_t samples, uint32_t frequency) {
    static uint32_t phase = 0;
    uint32_t half_period = 44100 / (frequency * 2);
    for (size_t i = 0; i < samples; i += 2) {
        int16_t sample;
        if ((phase / half_period) % 2 == 0) {
            sample = 1000;
        } else {
            sample = -1000;
        }
        // duplicate audio into L and R
        buffer[i] = sample;
        buffer[i + 1] = sample;
        phase++;
    }
}

int8_t ec11_read(gpio_num_t pin1, gpio_num_t pin2) {
    bool curr_pin1 = gpio_get_level(pin1);
    bool curr_pin2 = gpio_get_level(pin2);
    static bool prev_pin1 = curr_pin1; // set current read only on first run
    int8_t direction = 0;
    if (!curr_pin1 && prev_pin1) { // true when current read is LOW and previous read is HIGH
        if (curr_pin2) { // if pin2 is HIGH
            direction = 1;
        } else {
            direction = -1;
        }
    }
    prev_pin1 = curr_pin1;
    return direction;
}

std::atomic<int32_t> encoder_position = 0;
void ec11_read_task(void *arg) {
    while (true) {
        int8_t rotation = ec11_read(ec11_pin1, ec11_pin2);
        if (rotation == 1) {
            encoder_position++;
        } else if (rotation == -1) {
            encoder_position--;
        }
        vTaskDelay(1);
    }
}

/* unused
adc_oneshot_unit_handle_t adc_handle;
void setup_adc() {
    adc_oneshot_unit_init_cfg_t init_config = {};
    init_config.unit_id = ADC_UNIT_1;

    ESP_ERROR_CHECK(adc_oneshot_new_unit(&init_config, &adc_handle));

    adc_oneshot_chan_cfg_t channel_config = {};
    channel_config.bitwidth = ADC_BITWIDTH_DEFAULT;
    channel_config.atten = ADC_ATTEN_DB_12;

    ESP_ERROR_CHECK(adc_oneshot_config_channel(adc_handle,button_stack_adc_pin,&channel_config));
}

int8_t button_stack_read() {
    int v = 4000;
    adc_oneshot_read(adc_handle, button_stack_adc_pin, &v);
    if (debug) {ESP_LOGI(TAG, "Button stack value: %d", v);}
    if (v < 600) {
        return 0;
    } else if (v < 1600) {
        return 1;
    } else if (v < 2150) {
        return 2;
    } else if (v < 3000) {
        return 3;
    }
    return -1;
}

void setup_buzzer() {
    buzzer_timer.speed_mode = LEDC_LOW_SPEED_MODE;
    buzzer_timer.timer_num = LEDC_TIMER_0;
    buzzer_timer.duty_resolution = LEDC_TIMER_10_BIT;
    buzzer_timer.freq_hz = 1000;
    buzzer_timer.clk_cfg = LEDC_AUTO_CLK;
    ledc_timer_config(&buzzer_timer);
    buzzer_channel.gpio_num = buzzer_pin;
    buzzer_channel.speed_mode = LEDC_LOW_SPEED_MODE;
    buzzer_channel.channel = LEDC_CHANNEL_0;
    buzzer_channel.timer_sel = LEDC_TIMER_0;
    buzzer_channel.duty = 0;
    buzzer_channel.hpoint = 0;
    ledc_channel_config(&buzzer_channel);
}*/

void buzzer_tone(uint32_t f) {
    ledc_set_freq(LEDC_LOW_SPEED_MODE, LEDC_TIMER_0, f);
    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, 512);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
}

void buzzer_stop() {
    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, 0);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
}

void delay(int ms) {
    vTaskDelay(pdMS_TO_TICKS(ms));
}

extern "C" void app_main() {
    setup_gpio();
    i2s_setup(max98357a_blk, max98357a_ws, max98357a_data);
    uint32_t frequency = 440;
    xTaskCreate(ec11_read_task, "ec11_read_task", 2048, nullptr, 5, nullptr);
    int32_t position = encoder_position;
    int32_t prev_encoder_position = position;
    while (true) {
        position = encoder_position;
        frequency += (position - prev_encoder_position)*(10);
        bool button_pressed = !gpio_get_level(button_big_pin);
        if (button_pressed) {
            generate_test_tone(max98357a_buffer, 2048, frequency);
            i2s_write(max98357a_buffer, 2048 * sizeof(int16_t));
            ESP_LOGI(TAG, "playing speaker at freq: %d", frequency);
        } else {
            ESP_LOGI(TAG, "stopping speaker");
        }
        prev_encoder_position = position;
        delay(50);
    }
    /*
    setup_gpio();
    setup_buzzer();
    uint32_t current_tone = 500;
    xTaskCreate(ec11_read_task, "ec11_read_task", 2048, nullptr, 5, nullptr);
    int32_t position = encoder_position;
    int32_t prev_encoder_position = position;
    while (true) {
        position = encoder_position;
        ESP_LOGI(TAG, "position: %ld", position);
        current_tone += (position - prev_encoder_position)*(10);
        if (current_tone > 1000) {
            current_tone = 1000;
        } else if (current_tone < 100) {
            current_tone = 100;
        }
        bool button_pressed = !gpio_get_level(button_big_pin);
        if (button_pressed) {
            buzzer_tone(current_tone);
            ESP_LOGI(TAG, "playing current tone: %d", current_tone);
        } else {
            buzzer_stop();
            ESP_LOGI(TAG, "stopping current tone: %d", current_tone);
        }
        prev_encoder_position = position;
        delay(50);
    }*/
    /*while (true) {
        ESP_LOGI(TAG, "Button pressed: %d", !gpio_get_level(button_big_pin));
        int8_t pressed_button = button_stack_read();
        if (pressed_button != -1) {
            ESP_LOGI(TAG, "Button stack pressed: button %d", pressed_button);
        }
        if (pressed_button == 0) {
            buzzer_tone(500);
        } else if (pressed_button == 1) {
            buzzer_tone(750);
        } else if (pressed_button == 2) {
            buzzer_tone(1000);
        } else if (pressed_button == 3) {
            buzzer_tone(1500);
        } else {
            buzzer_stop();
        }
        delay(50);
    }*/


}